<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.opentmf.model</groupId>
    <artifactId>opentmf-v4-models</artifactId>
    <version>1.0.6-SNAPSHOT</version>
  </parent>

  <artifactId>opentmf-customer-v4-model</artifactId>
  <version>4.0.0.6-SNAPSHOT</version>
  <description>
        Common classes that are referenced from the following TMF artifacts:
    - TMF-629: Customer Management API, version: 4.0.0
    - TMF-632: Party Management API, version: 4.0.0
    - TMF-666: Account Management API, version: 4.0.0
    - TMF-669: Party Role Management API, version: 4.0.0
  </description>

  <dependencies>
    <dependency>
      <groupId>org.opentmf.model</groupId>
      <artifactId>opentmf-common-v4-model</artifactId>
      <version>4.1.0.6-SNAPSHOT</version>
    </dependency>
  </dependencies>

</project>