<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.opentmf.model</groupId>
    <artifactId>opentmf-v4-models</artifactId>
    <version>4.1.1</version>
  </parent>

  <artifactId>opentmf-699-v4-model</artifactId>
  <name>opentmf-699-v4-model</name>
  <version>4.0.0.11</version>
  <description>
    TMF-699: Sales Management API, version: 4.0.0
    Hierarchical model classes with polymorphism.
  </description>

  <dependencies>
    <dependency>
      <groupId>org.opentmf.model</groupId>
      <artifactId>opentmf-699-v4-api</artifactId>
      <version>4.0.0.11</version>
    </dependency>
    <dependency>
      <groupId>org.opentmf.model</groupId>
      <artifactId>opentmf-common-v4-model</artifactId>
      <version>4.2.0.11</version>
    </dependency>
  </dependencies>

</project>
