<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <parent>
    <groupId>org.opentmf.model</groupId>
    <artifactId>opentmf-v4-models</artifactId>
    <version>4.1.2-SNAPSHOT</version>
  </parent>

  <artifactId>opentmf-product-v4-model</artifactId>
  <name>opentmf-product-v4-model</name>
  <version>4.1.0.12-SNAPSHOT</version>
  <description>
    - TMF-620: Product Catalog Management API, version: 4.1.0
    - TMF-635: Usage Management API, version: 4.0.0
    - TMF-637: Product Inventory Management API, version: 4.0.0
    - TMF-658: Loyalty, version: 4.0.0
    - TMF-671: Promotion Management API, version: 4.1.0
    - TMF-677: Usage Consumption Management API, version: 4.0.0
    - TMF-679: Product Offering Qualification Management API, version: 4.0.0
  </description>

  <dependencies>
    <dependency>
      <groupId>org.opentmf.model</groupId>
      <artifactId>opentmf-product-v4-api</artifactId>
      <version>4.1.0.11</version>
    </dependency>
    <dependency>
      <groupId>org.opentmf.model</groupId>
      <artifactId>opentmf-common-v4-model</artifactId>
      <version>4.2.0.12-SNAPSHOT</version>
    </dependency>
  </dependencies>

</project>
